// <auto-generated />
using System;
using AplikacjaDeklaracji.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikacjaDeklaracji.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240328003829_MigracjaDodanieTabeliDeklaracja")]
    partial class MigracjaDodanieTabeliDeklaracja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AplikacjaDeklaracji.Models.DaneOsobowe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresEMail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Adres e-mail");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("date")
                        .HasColumnName("Data urodzenia");

                    b.Property<int>("DeklaracjaId")
                        .HasColumnType("int");

                    b.Property<string>("DrugieImie")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Drugie imie");

                    b.Property<string>("IdentyfikatorNip")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("Identyfikator NIP")
                        .IsFixedLength();

                    b.Property<string>("IdentyfikatorRegon")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("char(14)")
                        .HasColumnName("Identyfikator REGON")
                        .IsFixedLength();

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ImieMatki")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Imie matki");

                    b.Property<string>("ImieOjca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Imie ojca");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NrTelefonu")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .HasColumnName("Nr telefonu")
                        .IsFixedLength();

                    b.Property<string>("PelnaNazwa")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("Pelna Nazwa");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("DaneOsobowe", (string)null);
                });

            modelBuilder.Entity("AplikacjaDeklaracji.Models.Deklaracja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaneOsoboweId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DaneOsoboweId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Deklaracjas");
                });

            modelBuilder.Entity("AplikacjaDeklaracji.Models.Lokale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaneOsoboweId")
                        .HasColumnType("int");

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("Kod pocztowy")
                        .IsFixedLength();

                    b.Property<decimal?>("KosztOstateczny")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(22, 2)")
                        .HasColumnName("Koszt ostateczny")
                        .HasComputedColumnSql("(case when [Kwota zwolnienia]=NULL then [Stawka za os]*nullif([Liczba osob],(0)) else [Stawka za os]*nullif([Liczba osob],(0))-[Kwota zwolnienia] end)", false);

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("KwartalnaOplata")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(24, 2)")
                        .HasColumnName("Kwartalna oplata")
                        .HasComputedColumnSql("(case when [Kwota zwolnienia]=NULL then [Stawka za os]*nullif([Liczba osob],(0)) else [Stawka za os]*nullif([Liczba osob],(0))-[Kwota zwolnienia] end*(4))", false);

                    b.Property<decimal?>("KwotaZwolnienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Kwota zwolnienia")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("LiczbaOsob")
                        .HasColumnType("int")
                        .HasColumnName("Liczba osob");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("NrDomu")
                        .HasColumnType("int")
                        .HasColumnName("Nr domu");

                    b.Property<int?>("NrLokalu")
                        .HasColumnType("int")
                        .HasColumnName("Nr lokalu");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("StawkaZaOs")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Stawka za os");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("WysokoscOplaty")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)")
                        .HasColumnName("Wysokosc oplaty")
                        .HasComputedColumnSql("([Stawka za os]*nullif([Liczba osob],(0)))", false);

                    b.Property<decimal?>("WysokoscPoZwol")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(22, 2)")
                        .HasColumnName("Wysokosc po zwol")
                        .HasComputedColumnSql("([Stawka za os]*nullif([Liczba osob],(0))-[Kwota zwolnienia])", false);

                    b.HasKey("Id");

                    b.HasIndex("DaneOsoboweId");

                    b.ToTable("Lokale", (string)null);
                });

            modelBuilder.Entity("AplikacjaDeklaracji.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("AplikacjaDeklaracji.Models.Deklaracja", b =>
                {
                    b.HasOne("AplikacjaDeklaracji.Models.DaneOsobowe", "DaneOsobowe")
                        .WithOne("Deklaracja")
                        .HasForeignKey("AplikacjaDeklaracji.Models.Deklaracja", "DaneOsoboweId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplikacjaDeklaracji.Models.User", "User")
                        .WithMany("Deklaracje")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaneOsobowe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AplikacjaDeklaracji.Models.Lokale", b =>
                {
                    b.HasOne("AplikacjaDeklaracji.Models.DaneOsobowe", "DaneOsobowe")
                        .WithMany("Lokale")
                        .HasForeignKey("DaneOsoboweId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaneOsobowe");
                });

            modelBuilder.Entity("AplikacjaDeklaracji.Models.DaneOsobowe", b =>
                {
                    b.Navigation("Deklaracja")
                        .IsRequired();

                    b.Navigation("Lokale");
                });

            modelBuilder.Entity("AplikacjaDeklaracji.Models.User", b =>
                {
                    b.Navigation("Deklaracje");
                });
#pragma warning restore 612, 618
        }
    }
}
