//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class WyjatekTyp
    {
        
        private int kodField;
        
        private string komunikatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string komunikat
        {
            get
            {
                return this.komunikatField;
            }
            set
            {
                this.komunikatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class DokumentTyp
    {
        
        private string nazwaPlikuField;
        
        private string typPlikuField;
        
        private byte[] zawartoscField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nazwaPliku
        {
            get
            {
                return this.nazwaPlikuField;
            }
            set
            {
                this.nazwaPlikuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string typPliku
        {
            get
            {
                return this.typPlikuField;
            }
            set
            {
                this.typPlikuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] zawartosc
        {
            get
            {
                return this.zawartoscField;
            }
            set
            {
                this.zawartoscField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class DaneNadawcyTyp
    {
        
        private string uzytkownikField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string uzytkownik
        {
            get
            {
                return this.uzytkownikField;
            }
            set
            {
                this.uzytkownikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string system
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class DanePodmiotuTyp
    {
        
        private string identyfikatorField;
        
        private string typOsobyField;
        
        private string imieSkrotField;
        
        private string nazwiskoNazwaField;
        
        private string nipField;
        
        private string peselField;
        
        private string regonField;
        
        private bool zgodaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string identyfikator
        {
            get
            {
                return this.identyfikatorField;
            }
            set
            {
                this.identyfikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string typOsoby
        {
            get
            {
                return this.typOsobyField;
            }
            set
            {
                this.typOsobyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string imieSkrot
        {
            get
            {
                return this.imieSkrotField;
            }
            set
            {
                this.imieSkrotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nazwiskoNazwa
        {
            get
            {
                return this.nazwiskoNazwaField;
            }
            set
            {
                this.nazwiskoNazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nip
        {
            get
            {
                return this.nipField;
            }
            set
            {
                this.nipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pesel
        {
            get
            {
                return this.peselField;
            }
            set
            {
                this.peselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string regon
        {
            get
            {
                return this.regonField;
            }
            set
            {
                this.regonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool zgoda
        {
            get
            {
                return this.zgodaField;
            }
            set
            {
                this.zgodaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class StatusTyp
    {
        
        private int kodField;
        
        private string komunikatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string komunikat
        {
            get
            {
                return this.komunikatField;
            }
            set
            {
                this.komunikatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullPotwierdzTyp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullPobierzTyp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpowiedzPullOczekujaceTyp))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class OdpowiedzPullTyp
    {
        
        private StatusTyp statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StatusTyp status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class OdpowiedzPullPotwierdzTyp : OdpowiedzPullTyp
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class OdpowiedzPullPobierzTyp : OdpowiedzPullTyp
    {
        
        private DanePodmiotuTyp danePodmiotuField;
        
        private DaneNadawcyTyp daneNadawcyField;
        
        private System.DateTime dataNadaniaField;
        
        private string nazwaSkrytkiField;
        
        private string adresSkrytkiField;
        
        private string adresOdpowiedziField;
        
        private bool czyTestoweField;
        
        private byte[] daneDodatkoweField;
        
        private DokumentTyp dokumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DanePodmiotuTyp danePodmiotu
        {
            get
            {
                return this.danePodmiotuField;
            }
            set
            {
                this.danePodmiotuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DaneNadawcyTyp daneNadawcy
        {
            get
            {
                return this.daneNadawcyField;
            }
            set
            {
                this.daneNadawcyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime dataNadania
        {
            get
            {
                return this.dataNadaniaField;
            }
            set
            {
                this.dataNadaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nazwaSkrytki
        {
            get
            {
                return this.nazwaSkrytkiField;
            }
            set
            {
                this.nazwaSkrytkiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string adresSkrytki
        {
            get
            {
                return this.adresSkrytkiField;
            }
            set
            {
                this.adresSkrytkiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string adresOdpowiedzi
        {
            get
            {
                return this.adresOdpowiedziField;
            }
            set
            {
                this.adresOdpowiedziField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool czyTestowe
        {
            get
            {
                return this.czyTestoweField;
            }
            set
            {
                this.czyTestoweField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] daneDodatkowe
        {
            get
            {
                return this.daneDodatkoweField;
            }
            set
            {
                this.daneDodatkoweField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public DokumentTyp dokument
        {
            get
            {
                return this.dokumentField;
            }
            set
            {
                this.dokumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class OdpowiedzPullOczekujaceTyp : OdpowiedzPullTyp
    {
        
        private int oczekujaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int oczekujace
        {
            get
            {
                return this.oczekujaceField;
            }
            set
            {
                this.oczekujaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullPotwierdzTyp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullPobierzTyp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZapytaniePullOczekujaceTyp))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class ZapytaniePullTyp
    {
        
        private string podmiotField;
        
        private string nazwaSkrytkiField;
        
        private string adresSkrytkiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string podmiot
        {
            get
            {
                return this.podmiotField;
            }
            set
            {
                this.podmiotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nazwaSkrytki
        {
            get
            {
                return this.nazwaSkrytkiField;
            }
            set
            {
                this.nazwaSkrytkiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string adresSkrytki
        {
            get
            {
                return this.adresSkrytkiField;
            }
            set
            {
                this.adresSkrytkiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class ZapytaniePullPotwierdzTyp : ZapytaniePullTyp
    {
        
        private string skrotField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string skrot
        {
            get
            {
                return this.skrotField;
            }
            set
            {
                this.skrotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class ZapytaniePullPobierzTyp : ZapytaniePullTyp
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
    public partial class ZapytaniePullOczekujaceTyp : ZapytaniePullTyp
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.epuap.gov.pl/pull/", ConfigurationName="ServiceReference1.pull")]
    public interface pull
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/oczekujaceDokumenty", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WyjatekTyp), Action="http://ws.epuap.gov.pl/pull/oczekujaceDokumenty", Name="Wyjatek", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OdpowiedzPullTyp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZapytaniePullTyp))]
        System.Threading.Tasks.Task<ServiceReference1.oczekujaceDokumentyResponse> oczekujaceDokumentyAsync(ServiceReference1.oczekujaceDokumentyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/pobierzNastepny", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WyjatekTyp), Action="http://ws.epuap.gov.pl/pull/pobierzNastepny", Name="Wyjatek", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OdpowiedzPullTyp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZapytaniePullTyp))]
        System.Threading.Tasks.Task<ServiceReference1.pobierzNastepnyResponse> pobierzNastepnyAsync(ServiceReference1.pobierzNastepnyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.epuap.gov.pl/pull/potwierdzOdebranie", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.WyjatekTyp), Action="http://ws.epuap.gov.pl/pull/potwierdzOdebranie", Name="Wyjatek", Namespace="http://wsdl.epuap.gov.pl/obiekty/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OdpowiedzPullTyp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZapytaniePullTyp))]
        System.Threading.Tasks.Task<ServiceReference1.potwierdzOdebranieResponse> potwierdzOdebranieAsync(ServiceReference1.potwierdzOdebranieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class oczekujaceDokumentyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
        public ServiceReference1.ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace;
        
        public oczekujaceDokumentyRequest()
        {
        }
        
        public oczekujaceDokumentyRequest(ServiceReference1.ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace)
        {
            this.ZapytaniePullOczekujace = ZapytaniePullOczekujace;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class oczekujaceDokumentyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
        public ServiceReference1.OdpowiedzPullOczekujaceTyp OdpowiedzPullOczekujace;
        
        public oczekujaceDokumentyResponse()
        {
        }
        
        public oczekujaceDokumentyResponse(ServiceReference1.OdpowiedzPullOczekujaceTyp OdpowiedzPullOczekujace)
        {
            this.OdpowiedzPullOczekujace = OdpowiedzPullOczekujace;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pobierzNastepnyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
        public ServiceReference1.ZapytaniePullPobierzTyp ZapytaniePullPobierz;
        
        public pobierzNastepnyRequest()
        {
        }
        
        public pobierzNastepnyRequest(ServiceReference1.ZapytaniePullPobierzTyp ZapytaniePullPobierz)
        {
            this.ZapytaniePullPobierz = ZapytaniePullPobierz;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pobierzNastepnyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
        public ServiceReference1.OdpowiedzPullPobierzTyp OdpowiedzPullPobierz;
        
        public pobierzNastepnyResponse()
        {
        }
        
        public pobierzNastepnyResponse(ServiceReference1.OdpowiedzPullPobierzTyp OdpowiedzPullPobierz)
        {
            this.OdpowiedzPullPobierz = OdpowiedzPullPobierz;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class potwierdzOdebranieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
        public ServiceReference1.ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz;
        
        public potwierdzOdebranieRequest()
        {
        }
        
        public potwierdzOdebranieRequest(ServiceReference1.ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz)
        {
            this.ZapytaniePullPotwierdz = ZapytaniePullPotwierdz;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class potwierdzOdebranieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsdl.epuap.gov.pl/obiekty/", Order=0)]
        public ServiceReference1.OdpowiedzPullPotwierdzTyp OdpowiedzPullPotwierdz;
        
        public potwierdzOdebranieResponse()
        {
        }
        
        public potwierdzOdebranieResponse(ServiceReference1.OdpowiedzPullPotwierdzTyp OdpowiedzPullPotwierdz)
        {
            this.OdpowiedzPullPotwierdz = OdpowiedzPullPotwierdz;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface pullChannel : ServiceReference1.pull, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class pullClient : System.ServiceModel.ClientBase<ServiceReference1.pull>, ServiceReference1.pull
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public pullClient() : 
                base(pullClient.GetDefaultBinding(), pullClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.pull.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pullClient(EndpointConfiguration endpointConfiguration) : 
                base(pullClient.GetBindingForEndpoint(endpointConfiguration), pullClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pullClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(pullClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pullClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(pullClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public pullClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.oczekujaceDokumentyResponse> ServiceReference1.pull.oczekujaceDokumentyAsync(ServiceReference1.oczekujaceDokumentyRequest request)
        {
            return base.Channel.oczekujaceDokumentyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.oczekujaceDokumentyResponse> oczekujaceDokumentyAsync(ServiceReference1.ZapytaniePullOczekujaceTyp ZapytaniePullOczekujace)
        {
            ServiceReference1.oczekujaceDokumentyRequest inValue = new ServiceReference1.oczekujaceDokumentyRequest();
            inValue.ZapytaniePullOczekujace = ZapytaniePullOczekujace;
            return ((ServiceReference1.pull)(this)).oczekujaceDokumentyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.pobierzNastepnyResponse> ServiceReference1.pull.pobierzNastepnyAsync(ServiceReference1.pobierzNastepnyRequest request)
        {
            return base.Channel.pobierzNastepnyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.pobierzNastepnyResponse> pobierzNastepnyAsync(ServiceReference1.ZapytaniePullPobierzTyp ZapytaniePullPobierz)
        {
            ServiceReference1.pobierzNastepnyRequest inValue = new ServiceReference1.pobierzNastepnyRequest();
            inValue.ZapytaniePullPobierz = ZapytaniePullPobierz;
            return ((ServiceReference1.pull)(this)).pobierzNastepnyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.potwierdzOdebranieResponse> ServiceReference1.pull.potwierdzOdebranieAsync(ServiceReference1.potwierdzOdebranieRequest request)
        {
            return base.Channel.potwierdzOdebranieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.potwierdzOdebranieResponse> potwierdzOdebranieAsync(ServiceReference1.ZapytaniePullPotwierdzTyp ZapytaniePullPotwierdz)
        {
            ServiceReference1.potwierdzOdebranieRequest inValue = new ServiceReference1.potwierdzOdebranieRequest();
            inValue.ZapytaniePullPotwierdz = ZapytaniePullPotwierdz;
            return ((ServiceReference1.pull)(this)).potwierdzOdebranieAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.pull))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.pull))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.epuap.gov.pl/pk_external_ws/services/pull");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return pullClient.GetBindingForEndpoint(EndpointConfiguration.pull);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return pullClient.GetEndpointAddress(EndpointConfiguration.pull);
        }
        
        public enum EndpointConfiguration
        {
            
            pull,
        }
    }
}
